model_list:
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: ${ANTHROPIC_API_KEY}

litellm_settings:
  drop_params: true
  set_verbose: false

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
